run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - misspell

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write
      - (*encoding/json.Encoder).Encode
      - fmt.Fprintf
      - fmt.Sscanf
  gosec:
    excludes:
      - G204  # Subprocess with variable - we need to run ffmpeg
      - G306  # WriteFile permissions - 0644 is fine for configs
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - ifElseChain

issues:
  exclude-use-default: true
  exclude-dirs:
    - vendor
  exclude-rules:
    # Ignore unchecked errors in tests
    - path: _test\.go
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 5
